# Generated by Django 6.0.7 on 2026-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('competition', models.CharField(default='League', max_length=100)),
                ('match_date', models.DateField()),
                ('kickoff_time', models.TimeField()),
                ('venue', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=4)),
                ('stadium', models.CharField(default='Kipsolu Green Ground', max_length=150)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed')], default='UPCOMING', max_length=10)),
                ('our_score', models.PositiveIntegerField(blank=True, null=True)),
                ('opponent_score', models.PositiveIntegerField(blank=True, null=True)),
                ('match_report', models.TextField(blank=True, help_text='Optional short report, shown for completed matches')),
            ],
            options={
                'ordering': ['match_date', 'kickoff_time'],
            },
        ),
    ]
