# Generated by Django 5.0.6 on 2026-07-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="match_report",
        ),
    ]
