# Generated by Django 5.0.6 on 2026-07-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_match_match_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="competition",
            field=models.CharField(
                choices=[("FRIENDLY", "Friendly"), ("TOURNAMENT", "Tournament")],
                default="FRIENDLY",
                max_length=20,
            ),
        ),
    ]
