# Generated by Django 5.0.6 on 2026-07-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_alter_match_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_report",
            field=models.TextField(
                blank=True,
                help_text="Optional internal notes about the match. Not shown on the public site.",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="opponent_penalties",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match was not decided on penalties.",
                null=True,
                verbose_name="Opponent penalties",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="opponent_score_et",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match did not go to extra time.",
                null=True,
                verbose_name="Opponent score (after extra time)",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="our_penalties",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match was not decided on penalties.",
                null=True,
                verbose_name="Our penalties",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="our_score_et",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match did not go to extra time.",
                null=True,
                verbose_name="Our score (after extra time)",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="opponent_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Opponent score (normal time)"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="our_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Our score (normal time)"
            ),
        ),
        migrations.CreateModel(
            name="MatchGoalScorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        help_text="Minute the goal was scored, e.g. 45"
                    ),
                ),
                (
                    "is_extra_time",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this goal was scored during extra time.",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorers",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Scorer",
                "verbose_name_plural": "Goal Scorers",
                "ordering": ["minute"],
            },
        ),
    ]
