# Generated by Django 5.0.6 on 2026-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_match_match_report_match_opponent_penalties_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchgoalscorer",
            options={
                "ordering": ["id"],
                "verbose_name": "Goal Scorer",
                "verbose_name_plural": "Goal Scorers",
            },
        ),
        migrations.RemoveField(
            model_name="matchgoalscorer",
            name="minute",
        ),
        migrations.AddField(
            model_name="matchgoalscorer",
            name="is_penalty",
            field=models.BooleanField(
                default=False,
                help_text="Check if this goal was scored from a penalty kick.",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="stadium",
            field=models.CharField(default="Kipsolu Green Grounds", max_length=150),
        ),
    ]
