# Generated by Django 5.0.6 on 2026-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_alter_matchgoalscorer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchgoalscorer",
            options={
                "ordering": ["minute"],
                "verbose_name": "Goal Scorer",
                "verbose_name_plural": "Goal Scorers",
            },
        ),
        migrations.RemoveField(
            model_name="matchgoalscorer",
            name="is_penalty",
        ),
        migrations.AddField(
            model_name="matchgoalscorer",
            name="minute",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Minute the goal was scored, e.g. 45", null=True
            ),
        ),
    ]
