# Generated by Django 5.0.6 on 2026-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0006_alter_matchgoalscorer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchgoalscorer",
            options={
                "ordering": ["id"],
                "verbose_name": "Goal Scorer",
                "verbose_name_plural": "Goal Scorers",
            },
        ),
        migrations.RemoveField(
            model_name="matchgoalscorer",
            name="minute",
        ),
    ]
