# Generated by Django 5.0.6 on 2026-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0007_alter_matchgoalscorer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchgoalscorer",
            name="is_penalty",
            field=models.BooleanField(
                default=False,
                help_text="Check if this goal was scored during a penalty shootout.",
            ),
        ),
    ]
