# Generated by Django 5.0.6 on 2026-07-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0008_matchgoalscorer_is_penalty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="opponent",
            new_name="away_team",
        ),
        migrations.RemoveField(
            model_name="match",
            name="opponent_penalties",
        ),
        migrations.RemoveField(
            model_name="match",
            name="opponent_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="opponent_score_et",
        ),
        migrations.RemoveField(
            model_name="match",
            name="our_penalties",
        ),
        migrations.RemoveField(
            model_name="match",
            name="our_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="our_score_et",
        ),
        migrations.RemoveField(
            model_name="match",
            name="venue",
        ),
        migrations.AddField(
            model_name="match",
            name="away_penalties",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match was not decided on penalties.",
                null=True,
                verbose_name="Away team penalties",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="away_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Away team score (normal time)"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="away_score_et",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match did not go to extra time.",
                null=True,
                verbose_name="Away team score (after extra time)",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_penalties",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match was not decided on penalties.",
                null=True,
                verbose_name="Home team penalties",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Home team score (normal time)"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score_et",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank if the match did not go to extra time.",
                null=True,
                verbose_name="Home team score (after extra time)",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.CharField(default="Kipsolu Central FC", max_length=100),
        ),
        migrations.AddField(
            model_name="matchgoalscorer",
            name="team",
            field=models.CharField(
                choices=[("HOME", "Home team"), ("AWAY", "Away team")],
                default="HOME",
                help_text="Which side this goal was scored for.",
                max_length=4,
            ),
        ),
    ]
