# Generated by Django 6.0.7 on 2026-07-24 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=220, unique=True)),
                ('category', models.CharField(choices=[('MATCH', 'Match Report'), ('CLUB', 'Club News'), ('TRANSFER', 'Transfers'), ('COMMUNITY', 'Community')], default='CLUB', max_length=10)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown on listing pages', max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
