# Generated by Django 5.0.6 on 2026-07-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="taken_at",
            field=models.DateField(
                blank=True, help_text="Date the photo was taken (optional)", null=True
            ),
        ),
    ]
