# Generated by Django 5.0.6 on 2026-07-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_galleryimage_taken_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["-taken_at", "-uploaded_at"]},
        ),
    ]
