# Generated by Django 6.0.7 on 2026-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('squad_number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('nationality', models.CharField(default='Kenya', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, help_text='Height in centimetres', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('bio', models.TextField(blank=True)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0, help_text='Relevant for goalkeepers/defenders')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position', 'squad_number'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('HC', 'Head Coach'), ('AC', 'Assistant Coach'), ('GK', 'Goalkeeping Coach'), ('PHYS', 'Physiotherapist'), ('MGR', 'Team Manager'), ('OTH', 'Other Staff')], max_length=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['role', 'full_name'],
            },
        ),
    ]
