# Generated by Django 5.0.6 on 2026-07-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("HC", "Head Coach"),
                    ("AC", "Assistant Coach"),
                    ("MGR", "Team Manager"),
                    ("KM", "Kit manager"),
                ],
                max_length=4,
            ),
        ),
    ]
